# Generated by Django 5.2.17 on 2026-09-15 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_sandboxapiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxapiconfiguration',
            name='connection_status',
            field=models.CharField(default='unverified', max_length=30),
        ),
        migrations.AddField(
            model_name='sandboxapiconfiguration',
            name='credential_revision',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sandboxapiconfiguration',
            name='credentials_status',
            field=models.CharField(default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='sandboxapiconfiguration',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sandboxapiconfiguration',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sandboxapiconfiguration',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
