# Generated by Django 5.2.17 on 2026-09-05 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='Annual', max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='TRIAL', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_activation_date', models.DateField(blank=True, null=True)),
                ('previous_expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField()),
                ('new_expiry_date', models.DateField()),
                ('renewal_period', models.CharField(default='1 year', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LICENSE_ACTIVATED', 'LICENSE_ACTIVATED'), ('SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_RENEWED'), ('SUBSCRIPTION_EXPIRED', 'SUBSCRIPTION_EXPIRED'), ('SUBSCRIPTION_SUSPENDED', 'SUBSCRIPTION_SUSPENDED'), ('SUBSCRIPTION_REACTIVATED', 'SUBSCRIPTION_REACTIVATED')], max_length=30)),
                ('old_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
