# Generated by Django 5.2.17 on 2026-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalhistory',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
