import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="GSTImportBatch", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("return_type", models.CharField(choices=[("GSTR1", "GSTR-1 (B2B)"), ("GSTR2A", "GSTR-2A"), ("GSTR2B", "GSTR-2B")], max_length=10)), ("file_name", models.CharField(max_length=255)), ("file_type", models.CharField(max_length=20)), ("gstin", models.CharField(blank=True, max_length=15)), ("return_period", models.CharField(max_length=20)), ("total_records", models.PositiveIntegerField(default=0)), ("ready_records", models.PositiveIntegerField(default=0)), ("mapping_records", models.PositiveIntegerField(default=0)), ("duplicate_records", models.PositiveIntegerField(default=0)), ("error_records", models.PositiveIntegerField(default=0)), ("synced_records", models.PositiveIntegerField(default=0)), ("status", models.CharField(default="VALIDATED", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="GSTLedgerMapping", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("gstin", models.CharField(db_index=True, max_length=15)), ("gst_party_name", models.CharField(blank=True, max_length=255)), ("tally_ledger_name", models.CharField(max_length=255)), ("mapping_type", models.CharField(default="BOTH", max_length=20)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"constraints": [models.UniqueConstraint(fields=("gstin", "mapping_type"), name="unique_gstin_mapping_type")]}),
        migrations.CreateModel(name="GSTImportRecord", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("gstin", models.CharField(blank=True, db_index=True, max_length=15)), ("party_name", models.CharField(blank=True, max_length=255)), ("invoice_number", models.CharField(blank=True, max_length=100)), ("invoice_date", models.DateField(blank=True, null=True)), ("taxable_value", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("cgst", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("sgst", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("igst", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("cess", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("total_value", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("itc_value", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("tally_ledger_name", models.CharField(blank=True, max_length=255)), ("record_status", models.CharField(choices=[("READY", "Ready"), ("NEED_MAPPING", "Need mapping"), ("DUPLICATE", "Duplicate"), ("ERROR", "Error"), ("SYNCED", "Synced"), ("SYNC_FAILED", "Sync failed")], db_index=True, default="ERROR", max_length=20)), ("validation_message", models.TextField(blank=True)), ("raw_data", models.JSONField(default=dict)), ("is_selected", models.BooleanField(default=False)), ("is_synced", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="records", to="gst_tally.gstimportbatch"))], options={"indexes": [models.Index(fields=["gstin", "invoice_number", "invoice_date"], name="gst_tally_g_gstin_f46dd1_idx")]}),
        migrations.CreateModel(name="GSTSyncLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("sync_status", models.CharField(max_length=20)), ("request_payload", models.JSONField(default=dict)), ("response_payload", models.JSONField(default=dict)), ("error_message", models.TextField(blank=True)), ("synced_at", models.DateTimeField(auto_now_add=True)), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_logs", to="gst_tally.gstimportbatch")), ("import_record", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_logs", to="gst_tally.gstimportrecord"))]),
    ]
