# Generated by Django 5.2.17 on 2026-08-20 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0003_complete_license_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('registration_status', models.CharField(blank=True, max_length=50)),
                ('taxpayer_type', models.CharField(blank=True, max_length=50)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gst_party_tbl',
            },
        ),
        migrations.RemoveField(
            model_name='gstimportrecord',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='duplicate_records',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='error_records',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='mapping_records',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='ready_records',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='return_period',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='return_type',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='synced_records',
        ),
        migrations.RemoveField(
            model_name='gstimportbatch',
            name='total_records',
        ),
        migrations.AddField(
            model_name='gstimportbatch',
            name='failed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gstimportbatch',
            name='gst_return_type',
            field=models.CharField(choices=[('GSTR1', 'GSTR-1 (B2B)'), ('GSTR2A', 'GSTR-2A'), ('GSTR2B', 'GSTR-2B')], default='GSTR1', max_length=10),
        ),
        migrations.AddField(
            model_name='gstimportbatch',
            name='imported_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gstimportbatch',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gstimportbatch',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='gstimportbatch',
            name='file_type',
            field=models.CharField(choices=[('JSON', 'JSON'), ('CSV', 'CSV'), ('EXCEL', 'Excel')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='gstimportbatch',
            table='gst_import_batch_tbl',
        ),
        migrations.CreateModel(
            name='GSTInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('invoice_no', models.CharField(max_length=100)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('reverse_charge', models.CharField(blank=True, max_length=10)),
                ('invoice_type', models.CharField(blank=True, max_length=30)),
                ('filing_period', models.CharField(blank=True, max_length=20)),
                ('filing_type', models.CharField(blank=True, max_length=20)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='gst_tally.gstimportbatch')),
            ],
            options={
                'db_table': 'gst_invoice_tbl',
            },
        ),
        migrations.AlterField(
            model_name='gstsynclog',
            name='import_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='gst_tally.gstinvoice'),
        ),
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['customer_gstin'], name='gst_inv_gstin_idx'),
        ),
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['invoice_no'], name='gst_inv_no_idx'),
        ),
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['invoice_date'], name='gst_inv_date_idx'),
        ),
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['source_type'], name='gst_inv_source_idx'),
        ),
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['filing_period'], name='gst_inv_period_idx'),
        ),
        migrations.DeleteModel(
            name='GSTImportRecord',
        ),
    ]
