# Generated by Django 5.2.17 on 2026-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0018_tally_company_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstimportbatch',
            name='source_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gstimportbatch',
            name='tax_period',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='gstimportbatch',
            index=models.Index(fields=['company_gstin', 'gst_return_type', 'tax_period', 'source_fingerprint'], name='gst_batch_dup_scope_idx'),
        ),
    ]
