# Generated by Django 5.2.17 on 2026-08-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0019_gstimportbatch_source_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallycompanymapping',
            name='license_administrator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tallycompanymapping',
            name='license_serial',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
