# Generated by Django 5.2.17 on 2026-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0022_gstparty_lookup_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstinvoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='supplier_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['supplier_gstin'], name='gst_inv_supp_gstin_idx'),
        ),
    ]
