# Generated by Django 5.2.17 on 2026-09-04 13:20

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0023_gstinvoice_customer_name_gstinvoice_supplier_gstin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('verification_pending', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('current_invoice', models.CharField(blank=True, max_length=100)),
                ('result', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_import_jobs', to='gst_tally.gstimportbatch')),
            ],
            options={
                'db_table': 'tally_import_job_tbl',
                'indexes': [models.Index(fields=['batch', 'status'], name='tally_import_job_batch_idx')],
            },
        ),
    ]
