# Generated by Django 5.2.17 on 2026-09-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0025_gstimportbatch_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyimportjob',
            name='pause_requested',
            field=models.BooleanField(default=False),
        ),
    ]
