# Generated by Django 5.2.17 on 2026-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0030_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstimportbatch',
            name='duplicate_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='dedup_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
