# Generated by Django 5.2.17 on 2026-09-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0031_gstimportbatch_duplicate_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyimportjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
