# Generated by Codex on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gst_tally", "0032_tallyimportjob_error_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTCompanyImportSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("company_gstin", models.CharField(max_length=15)),
                ("return_type", models.CharField(max_length=10)),
                ("transaction_type", models.CharField(max_length=20)),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("source_format", models.CharField(blank=True, max_length=10)),
                ("import_scope_hash", models.CharField(max_length=64)),
                ("total_source_count", models.PositiveIntegerField(default=0)),
                ("successful_voucher_count", models.PositiveIntegerField(default=0)),
                ("failed_record_count", models.PositiveIntegerField(default=0)),
                ("needs_attention_count", models.PositiveIntegerField(default=0)),
                ("skipped_duplicate_count", models.PositiveIntegerField(default=0)),
                ("pending_record_count", models.PositiveIntegerField(default=0)),
                ("first_uploaded_at", models.DateTimeField(default=timezone.now)),
                ("last_uploaded_at", models.DateTimeField(default=timezone.now)),
                ("first_tally_import_at", models.DateTimeField(blank=True, null=True)),
                ("last_tally_import_at", models.DateTimeField(blank=True, null=True)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("import_status", models.CharField(default="PENDING", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gst_company_import_summary_tbl",
                "indexes": [
                    models.Index(fields=["company_gstin", "return_type"], name="gst_summary_company_return_idx"),
                    models.Index(fields=["import_status"], name="gst_summary_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=["company_gstin", "return_type", "import_scope_hash"], name="uniq_gst_company_summary"),
                ],
            },
        ),
        migrations.AddField(
            model_name="gstimportbatch",
            name="company_import_summary",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="batches", to="gst_tally.gstcompanyimportsummary"),
        ),
        migrations.CreateModel(
            name="GSTTallyVoucherRegistry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_gstin", models.CharField(max_length=15)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("return_type", models.CharField(max_length=10)),
                ("transaction_type", models.CharField(max_length=20)),
                ("party_gstin", models.CharField(max_length=15)),
                ("invoice_number", models.CharField(max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("voucher_identity_hash", models.CharField(max_length=64)),
                ("import_status", models.CharField(default="PENDING", max_length=30)),
                ("tally_created", models.BooleanField(default=False)),
                ("tally_altered", models.BooleanField(default=False)),
                ("tally_voucher_identifier", models.CharField(blank=True, max_length=255)),
                ("first_seen_at", models.DateTimeField(default=timezone.now)),
                ("last_seen_at", models.DateTimeField(default=timezone.now)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("import_summary", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="voucher_registry", to="gst_tally.gstcompanyimportsummary")),
                ("latest_invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="voucher_registry_entries", to="gst_tally.gstinvoice")),
            ],
            options={
                "db_table": "gst_tally_voucher_registry_tbl",
                "indexes": [
                    models.Index(fields=["company_gstin", "return_type"], name="gst_reg_company_return_idx"),
                    models.Index(fields=["import_status"], name="gst_registry_status_idx"),
                    models.Index(fields=["voucher_identity_hash"], name="gst_registry_hash_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=["company_gstin", "return_type", "voucher_identity_hash"], name="uniq_gst_voucher_registry"),
                ],
            },
        ),
    ]
