# Generated by Django 5.2.17 on 2026-09-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0034_company_scope_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstcompanyimportsummary',
            name='company_scope_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gstimportbatch',
            name='company_scope_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gsttallyvoucherregistry',
            name='company_scope_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
