# Generated by Django 5.2.17 on 2026-09-15 12:55

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0036_scope_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTallyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('detected_serial', models.CharField(blank=True, max_length=64)),
                ('detected_company_gstin', models.CharField(blank=True, max_length=15)),
                ('detected_company_name', models.CharField(blank=True, max_length=255)),
                ('tally_reachable', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'local_tally_agent_tbl',
            },
        ),
        migrations.CreateModel(
            name='LocalTallyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'local_tally_job_tbl',
            },
        ),
        migrations.AddField(
            model_name='gstimportbatch',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='is_carry_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='original_period',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='posting_period',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['is_carry_forward', 'posting_period'], name='gst_inv_carry_period_idx'),
        ),
        migrations.AddField(
            model_name='localtallyagent',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_tally_agent', to='gst_tally.licenseddevice'),
        ),
        migrations.AddField(
            model_name='localtallyjob',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='gst_tally.localtallyagent'),
        ),
        migrations.AddField(
            model_name='localtallyjob',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_agent_jobs', to='gst_tally.gstimportbatch'),
        ),
        migrations.AddIndex(
            model_name='localtallyagent',
            index=models.Index(fields=['detected_company_gstin', 'last_seen_at'], name='agent_gstin_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='localtallyjob',
            index=models.Index(fields=['agent', 'status', 'created_at'], name='agent_job_claim_idx'),
        ),
    ]
