# Generated by Django 5.2.17 on 2026-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0039_import_session_retention_24h'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gstinvoice',
            index=models.Index(fields=['import_batch', 'id'], name='gst_inv_batch_page_idx'),
        ),
    ]
