# Generated by Django 5.2.17 on 2026-09-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0041_preview_filter_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gstinvoice',
            name='gst_inv_batch_no_idx',
        ),
        migrations.RemoveIndex(
            model_name='gstinvoice',
            name='gst_inv_batch_gstin_idx',
        ),
    ]
