# Generated by Django 5.2.17 on 2026-09-18 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0042_remove_gstinvoice_gst_inv_batch_no_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localtallyagent',
            name='identity',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='localtallyagent',
            name='installation_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='localtallyjob',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConnectorEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('installation_id', models.UUIDField()),
                ('poll_hash', models.CharField(max_length=64)),
                ('proof_hash', models.CharField(max_length=64)),
                ('browser_device', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gst_tally.localtallyagent')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connector_enrollment_tbl',
            },
        ),
    ]
