# Generated by Django 5.2.17 on 2026-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tally', '0043_localtallyagent_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtallyagent',
            name='browser_device',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
