from django.urls import path
from superadmin.views import CustomerSupportContactView
from .views import (BatchCompanyView, BatchDetailView, BatchListView, BatchPartiesView, BatchPartyDetailView, BatchPreviewView, ChangePasswordView, CompanyVerifyView,
                    ImportView, MyProfileView, SourcePreviewView, BatchPreviewPdfView, TallyConnectionView, TallyDiagnosticsView, TallyImportActiveJobView,
                    TallyImportJobPauseView, TallyImportJobResumeView, TallyImportJobStatusView, TallyImportView, TallyLicenseView,
                    ProductLicenseActivateView, ProductLicenseHeartbeatView, ProductLicensePreImportCheckView, ProductLicenseVerifyView,
                    TallyMastersView, TallyVoucherCorrectionView, TallyVoucherPreviewView,
                    LocalTallyAgentProvisionView, LocalTallyAgentHeartbeatView, LocalTallyAgentStatusView, LocalTallyAgentNextJobView, LocalTallyAgentJobResultView)

urlpatterns = [
    path("preview/", SourcePreviewView.as_view()), path("import/", ImportView.as_view()),
    path("batches/", BatchListView.as_view()), path("batches/<int:pk>/", BatchDetailView.as_view()),
    path("batches/<int:pk>/preview/", BatchPreviewView.as_view()),
    path("batches/<int:pk>/preview/pdf/", BatchPreviewPdfView.as_view()),
    path("import-batches/<int:pk>/fetch-parties/", BatchPartiesView.as_view()),
    path("import-batches/<int:pk>/parties/", BatchPartiesView.as_view()),
    path("import-batches/<int:pk>/parties/<str:gstin>/", BatchPartyDetailView.as_view()),
    path("import-batches/<int:pk>/company/", BatchCompanyView.as_view()),
    path("import-batches/<int:pk>/company/verify/", CompanyVerifyView.as_view()),
    path("import-batches/<int:pk>/tally-masters/prepare/", TallyMastersView.as_view()),
    path("import-batches/<int:pk>/tally-license/verify/", TallyLicenseView.as_view()),
    path("tally/connection/", TallyConnectionView.as_view()),
    path("tally/diagnostics/", TallyDiagnosticsView.as_view()),
    path("import-batches/<int:pk>/tally-vouchers/preview/", TallyVoucherPreviewView.as_view()),
    path("import-batches/<int:pk>/tally-vouchers/correct/", TallyVoucherCorrectionView.as_view()),
    path("import-batches/<int:pk>/tally-import/", TallyImportView.as_view()),
    path("import-batches/<int:pk>/tally-import/active-job/", TallyImportActiveJobView.as_view()),
    path("import-batches/<int:pk>/license/pre-import-check/", ProductLicensePreImportCheckView.as_view()),
    path("tally-import/jobs/<str:job_id>/", TallyImportJobStatusView.as_view()),
    path("tally-import/jobs/<str:job_id>/pause/", TallyImportJobPauseView.as_view()),
    path("tally-import/jobs/<str:job_id>/resume/", TallyImportJobResumeView.as_view()),
    path("license/activate/", ProductLicenseActivateView.as_view()),
    path("license/verify/", ProductLicenseVerifyView.as_view()),
    path("license/heartbeat/", ProductLicenseHeartbeatView.as_view()),
    path("local-agent/provision/", LocalTallyAgentProvisionView.as_view()),
    path("local-agent/status/", LocalTallyAgentStatusView.as_view()),
    path("local-agent/heartbeat/", LocalTallyAgentHeartbeatView.as_view()),
    path("local-agent/next-job/", LocalTallyAgentNextJobView.as_view()),
    path("local-agent/jobs/<uuid:job_id>/result/", LocalTallyAgentJobResultView.as_view()),
    path("me/profile/", MyProfileView.as_view()),
    path("me/change-password/", ChangePasswordView.as_view()),
    path("support-contact/", CustomerSupportContactView.as_view()),
]
